### ISSUE TITLE
Tag Pixel Experience ROMs as discontinued

### ISSUE THREAD

**Issue by d3radicated** [Customrombay/database#33]
https://blog.pixelexperience.org/2024/04/everything-has-to-come-to-an-end-sometime/

**Comment by PiotrZPL** [comment]
Yeah, unfortunate. I will mark PE as discontinued soon.

**Comment by PiotrZPL** [comment]
Resolved in [72e2883](https://github.com/Customrombay/database/commit/72e2883d6b5d9f7b9cc04708be8800f1e2a71c8f).

**Comment by PeppeMonster** [comment]
@PiotrZPL do not forget to update Readme file
