### ISSUE TITLE
[Request] Add CalyxOS

### ISSUE THREAD

**Issue by HemanthJabalpuri** [Customrombay/database#9]
@PiotrZPL 

CalyxOS is now available for Moto G32/42/52. It would be great if it is listed in your database.

- https://github.com/CalyxOS/calyxos.org/blob/main/pages/_data/devices.yml

- https://github.com/CalyxOS/calyxos.org/blob/main/pages/_data/downloads.yml

Maybe this will help for reference https://azadidroid.app/model/rhode

Thanks

**Comment by PiotrZPL** [comment]
Resolved by [PR#11](https://github.com/Customrombay/database/pull/11). A syncing script will be added in the future.
